### ISSUE TITLE
Is input shape still YXZ ?

### ISSUE THREAD

**Issue by Inspirateur** [cgerikj/binary-greedy-meshing#21]
Hi, I'm trying to port this library to Rust, but something weird happens when I run it
```rust
fn linearize(x: usize, y: usize, z: usize) -> usize {
    // Note that this is YXZ order
    y + x*CS_P + z*CS_P2
}

fn test() {
  // Put 1 voxel in position 0, 0, 0 (=1, 1, 1 with padding) and 1 voxel right above it
  let mut voxels: [u16; 262144] = [0; CS_P2*CS_P];
  voxels[linearize(1, 1, 1)] = 1;
  voxels[linearize(1, 2, 1)] = 1;
  let mut mesh_data = MeshData::new(CS);
  // Fill the opacity mask 
  ...
  mesh(&voxels, &mut mesh_data);
  // Inspect the quads we got
  ...
}
```
The algorithm outputs 6 quads as predicted (the 2 block got "merged") but something is wrong when inspecting the quad data:
```
Quad { x: 0, y: 1, z: 0, w: 1, h: 2 }
Quad { x: 1, y: 0, z: 0, w: 1, h: 2 }
Quad { x: 1, y: 1, z: 0, w: 1, h: 2 }
Quad { x: 0, y: 0, z: 0, w: 1, h: 2 }
Quad { x: 1, y: 0, z: 2, w: 1, h: 1 }
Quad { x: 0, y: 0, z: 0, w: 1, h: 1 }
```
I would expect the top quad to have Y = 2 but instead it has Z = 2.

I saw that in the Readme of the v1.0.0 branch the shape was stated to be YXZ, but since I got this weird result and the input shape is not specified in the new Readme I'm asking the question: is the input shape still supposed to be YXZ ? or did it change to XYZ in v2 ?

**Comment by cgerikj** [comment]
Thank you for letting me know! It should be ZXY instead of YXZ.

Fixed the function name: https://github.com/cgerikj/binary-greedy-meshing/commit/42caaaee2aa706afc181b214003a38ab7a7ea0b4
